const fs = require('fs');

const pineIdePath = 'e:\\TRADINGVIEW ADVANCED\\pine_editor_ide.js';
let c = fs.readFileSync(pineIdePath, 'utf8');

const BUILTIN_TECHNICALS = [
  "52 Week High/Low",
  "Accelerator Oscillator",
  "Accumulation/Distribution",
  "Accumulative Swing Index",
  "Advance/Decline",
  "Arnaud Legoux Moving Average",
  "Aroon",
  "Average Directional Index",
  "Average Price",
  "Average True Range",
  "Awesome Oscillator",
  "Balance of Power",
  "Bollinger Bands",
  "Bollinger Bands %B",
  "Bollinger Bands Width",
  "Chaikin Money Flow",
  "Chaikin Oscillator",
  "Chaikin Volatility",
  "Chande Kroll Stop",
  "Chande Momentum Oscillator",
  "Chop Zone",
  "Choppiness Index",
  "Commodity Channel Index",
  "Connors RSI",
  "Coppock Curve",
  "Correlation - Log",
  "Correlation Coefficient",
  "Detrended Price Oscillator",
  "Directional Movement",
  "Donchian Channels",
  "Double EMA",
  "Ease Of Movement",
  "Elder's Force Index",
  "EMA Cross",
  "Envelopes",
  "Fisher Transform",
  "Guppy Multiple Moving Average",
  "Historical Volatility",
  "Hull Moving Average",
  "Ichimoku Cloud",
  "Keltner Channels",
  "Klinger Oscillator",
  "Know Sure Thing",
  "Least Squares Moving Average",
  "Linear Regression Curve",
  "Linear Regression Slope",
  "MA Cross",
  "MA with EMA Cross",
  "MACD",
  "Majority Rule",
  "Mass Index",
  "McGinley Dynamic",
  "Median Price",
  "Momentum",
  "Money Flow Index",
  "Moving Average",
  "Moving Average Adaptive",
  "Moving Average Channel",
  "Moving Average Double",
  "Moving Average Exponential",
  "Moving Average Hamming",
  "Moving Average Multiple",
  "Moving Average Triple",
  "Moving Average Weighted",
  "Net Volume",
  "On Balance Volume",
  "Parabolic SAR",
  "Pivot Points Standard",
  "Price Channel",
  "Price Oscillator",
  "Price Volume Trend",
  "Rank Correlation Index",
  "Rate Of Change",
  "Ratio",
  "Relative Strength Index",
  "Relative Vigor Index",
  "Relative Volatility Index",
  "SMI Ergodic Indicator/Oscillator",
  "Smoothed Moving Average",
  "Spread",
  "Standard Deviation",
  "Standard Error",
  "Standard Error Bands",
  "Stochastic",
  "Stochastic RSI",
  "SuperTrend",
  "Trend Strength Index",
  "Triple EMA",
  "TRIX",
  "True Strength Index",
  "Typical Price",
  "Ultimate Oscillator",
  "Volatility Close-to-Close",
  "Volatility Index",
  "Volatility O-H-L-C",
  "Volatility Zero Trend Close-to-Close",
  "Volume",
  "Volume Oscillator",
  "Volume Profile Fixed Range",
  "Volume Profile Visible Range",
  "Vortex Indicator",
  "VWAP",
  "VWMA",
  "Williams %R",
  "Williams Alligator",
  "Williams Fractal",
  "Zig Zag"
];

const target = '  let _activeIndicatorsCategory = ';
const idx = c.indexOf(target);

if (idx === -1) {
  console.error('Target not found');
  process.exit(1);
}

const def = '  const BUILTIN_TECHNICALS = ' + JSON.stringify(BUILTIN_TECHNICALS, null, 2) + ';\n\n';
c = c.substring(0, idx) + def + c.substring(idx);
fs.writeFileSync(pineIdePath, c, 'utf8');
console.log('Successfully inserted BUILTIN_TECHNICALS declaration into pine_editor_ide.js');
